CREATE TABLE insured_person (
        id integer generated by default as identity,
        first_name varchar(255),
        premium numeric(38,2),
        second_name varchar(255),
        primary key (id)
    );

CREATE TABLE policy (
        id integer generated by default as identity,
        created_at bigint not null,
        external_id varchar(255),
        start_date date,
        primary key (id)
 );

CREATE index idx_on_policy_for_external_id_and_start_date on policy (external_id, start_date);


 CREATE TABLE policy_insured_person (
        policy_internal_id integer not null,
        person_id integer not null
    );

ALTER TABLE policy_insured_person
       add constraint foreign_key_policy_person_person_id
       foreign key (person_id)
       references insured_person;


ALTER TABLE policy_insured_person
       add constraint foreign_key_policy_insured_person_policy_internal_id
       foreign key (policy_internal_id)
       references policy;
